/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : ItemId,
  'title' : string,
  'content' : string,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : string,
}
export type AuthorId = bigint;
export type ItemId = bigint;
export interface Song {
  'id' : ItemId,
  'title' : string,
  'lyrics' : string,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : string,
}
export type Time = bigint;
export interface Writing {
  'id' : ItemId,
  'title' : string,
  'content' : string,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : string,
}
export interface _SERVICE {
  'addArticle' : ActorMethod<[string, string, AuthorId, string, Time], ItemId>,
  'addSong' : ActorMethod<[string, string, AuthorId, string, Time], ItemId>,
  'addWriting' : ActorMethod<[string, string, AuthorId, string, Time], ItemId>,
  'getArticleById' : ActorMethod<[ItemId], Article>,
  'getSongById' : ActorMethod<[ItemId], Song>,
  'getWritingById' : ActorMethod<[ItemId], Writing>,
  'listAllArticles' : ActorMethod<[], Array<Article>>,
  'listAllSongs' : ActorMethod<[], Array<Song>>,
  'listAllWritings' : ActorMethod<[], Array<Writing>>,
  'listArticlesByAuthor' : ActorMethod<[AuthorId], Array<Article>>,
  'listSongsByAuthor' : ActorMethod<[AuthorId], Array<Song>>,
  'listWritingsByAuthor' : ActorMethod<[AuthorId], Array<Writing>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];