/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AuthorId = IDL.Nat;
export const Time = IDL.Int;
export const ItemId = IDL.Nat;
export const Article = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : IDL.Text,
});
export const Song = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : IDL.Text,
});
export const Writing = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : AuthorId,
  'published' : Time,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addArticle' : IDL.Func(
      [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
      [ItemId],
      [],
    ),
  'addSong' : IDL.Func(
      [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
      [ItemId],
      [],
    ),
  'addWriting' : IDL.Func(
      [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
      [ItemId],
      [],
    ),
  'getArticleById' : IDL.Func([ItemId], [Article], ['query']),
  'getSongById' : IDL.Func([ItemId], [Song], ['query']),
  'getWritingById' : IDL.Func([ItemId], [Writing], ['query']),
  'listAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'listAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'listAllWritings' : IDL.Func([], [IDL.Vec(Writing)], ['query']),
  'listArticlesByAuthor' : IDL.Func([AuthorId], [IDL.Vec(Article)], ['query']),
  'listSongsByAuthor' : IDL.Func([AuthorId], [IDL.Vec(Song)], ['query']),
  'listWritingsByAuthor' : IDL.Func([AuthorId], [IDL.Vec(Writing)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AuthorId = IDL.Nat;
  const Time = IDL.Int;
  const ItemId = IDL.Nat;
  const Article = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : AuthorId,
    'published' : Time,
    'author' : IDL.Text,
  });
  const Song = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'authorId' : AuthorId,
    'published' : Time,
    'author' : IDL.Text,
  });
  const Writing = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : AuthorId,
    'published' : Time,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addArticle' : IDL.Func(
        [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
        [ItemId],
        [],
      ),
    'addSong' : IDL.Func(
        [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
        [ItemId],
        [],
      ),
    'addWriting' : IDL.Func(
        [IDL.Text, IDL.Text, AuthorId, IDL.Text, Time],
        [ItemId],
        [],
      ),
    'getArticleById' : IDL.Func([ItemId], [Article], ['query']),
    'getSongById' : IDL.Func([ItemId], [Song], ['query']),
    'getWritingById' : IDL.Func([ItemId], [Writing], ['query']),
    'listAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'listAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'listAllWritings' : IDL.Func([], [IDL.Vec(Writing)], ['query']),
    'listArticlesByAuthor' : IDL.Func(
        [AuthorId],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'listSongsByAuthor' : IDL.Func([AuthorId], [IDL.Vec(Song)], ['query']),
    'listWritingsByAuthor' : IDL.Func(
        [AuthorId],
        [IDL.Vec(Writing)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };